
sudo: required
dist: trusty  # Ubuntu 14.04
language: cpp

before_install:
    - unset CC
    - unset CXX
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install gcc-6 g++-6  # TODO all the different compilers
    - export CC=gcc-6
    - export CXX=g++-6

script:
    - make tests

