
language: generic
sudo: required
services:
    - docker

before_install:
    - docker pull primordus/ubuntu-c-cxx-dev
    - docker run -d primordus/ubuntu-c-cxx-dev tail -f /dev/null
    - docker ps -a
    - docker cp . $(docker ps -ql):/tmp/

env:
    - CC=gcc-4.9 CXX=g++-4.9
    - CC=gcc-5 CXX=g++-5
    - CC=gcc-6 CXX=g++-6
    - CC=clang-3.6 CXX=clang++-3.6
    - CC=clang-3.7 CXX=clang++-3.7
    - CC=clang-3.8 CXX=clang++-3.8

script:
    - docker exec $(docker ps -ql) /bin/sh -c "cd /tmp && CC=${CC} CXX=${CXX} make tests"

