
sudo: required
language: cpp

before_install:
    - unset CC
    - unset CXX
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install gcc-5 g++-5  # TODO all the different compilers
    - export CC=gcc-5
    - export CXX=g++-5

script:
    - make tests

